// lib/services-data.ts
import {
  FlaskConical, Droplets, Microscope, Bug, Shield, Activity, TestTube,
  Dna, HeartPulse
} from "lucide-react";

export const servicesData = [
  {
    id: "clinical-chemistry",
    slug: "clinical-chemistry",
    icon: FlaskConical,
    title: "Clinical Chemistry",
    fullTitle: "Clinical Chemistry Services",
    shortDescription: "Blood glucose, liver & kidney function tests, lipid profile, and metabolic assessments.",
    description: "Analysis of blood and body fluids to evaluate organ function, metabolic status, and biochemical balance.",
    detailedDescription: `Clinical chemistry forms the backbone of modern diagnostics. Our department is equipped with fully automated, high-throughput analyzers that deliver accurate results for over 50 biochemical parameters.\n\nWe provide essential testing for diabetes management, liver and kidney health, cardiovascular risk assessment, electrolyte balance, and nutritional status evaluation – helping physicians make timely and effective clinical decisions. Quality control is maintained through daily calibration and external proficiency testing.`,
    tests: [
      { name: "Blood Glucose (Fasting)", code: "FBS", turnaround: "Same Day", price: "15,000" },
      { name: "Blood Glucose (Random)", code: "RBS", turnaround: "Same Day", price: "15,000" },
      { name: "Blood Glucose (Post-Prandial)", code: "PPBS", turnaround: "Same Day", price: "15,000" },
      { name: "Liver Function Tests (LFT)", code: "LFT", turnaround: "Same Day", price: "45,000" },
      { name: "Kidney Function Tests (KFT)", code: "KFT", turnaround: "Same Day", price: "40,000" },
      { name: "Lipid Profile", code: "LIPID", turnaround: "Same Day", price: "35,000" },
      { name: "HbA1c (Glycated Hemoglobin)", code: "HBA1C", turnaround: "Same Day", price: "35,000" },
      { name: "Electrolytes Panel", code: "ELEC", turnaround: "Same Day", price: "30,000" },
      { name: "Uric Acid", code: "UA", turnaround: "Same Day", price: "12,000" },
      { name: "Creatinine", code: "CREAT", turnaround: "Same Day", price: "12,000" },
      { name: "Blood Urea Nitrogen", code: "BUN", turnaround: "Same Day", price: "12,000" },
      { name: "Calcium & Phosphorus", code: "CA-PO4", turnaround: "Same Day", price: "25,000" },
      { name: "Total Protein", code: "TP", turnaround: "Same Day", price: "15,000" },
      { name: "Albumin", code: "ALB", turnaround: "Same Day", price: "12,000" },
      { name: "Bilirubin (Total & Direct)", code: "BILI", turnaround: "Same Day", price: "20,000" },
    ],
    benefits: [
      "Early detection of metabolic disorders",
      "Monitoring of chronic conditions like diabetes",
      "Assessment of organ function (liver, kidney)",
      "Nutritional status evaluation",
      "Drug level monitoring and toxicity screening",
      "Cardiovascular risk assessment",
    ],
    preparation: "Most tests require 8-12 hours fasting. Avoid alcohol 24 hours before testing. Continue medications unless advised otherwise by your doctor.",
    image: "/laboratory-blood-test-analysis-medical-equipment.jpg",
  },
  {
    id: "hematology",
    slug: "hematology",
    icon: Droplets,
    title: "Hematology",
    fullTitle: "Hematology Services",
    shortDescription: "Complete blood analysis, anemia diagnosis, and clotting mechanism evaluation.",
    description: "Detailed analysis of blood cells and clotting factors for diagnosis of blood disorders.",
    detailedDescription: `Hematology is essential for diagnosing and monitoring blood disorders, infections, anemia, and clotting abnormalities. Our lab uses 5-part differential automated analyzers and expert microscopic review to provide comprehensive hematology reports.\n\nWe offer specialized testing for sickle cell disease, bleeding disorders, and pre-surgical coagulation profiles – critical for patient safety and effective treatment. All analyses are performed with strict quality control.`,
    tests: [
      { name: "Complete Blood Count (CBC)", code: "CBC", turnaround: "Same Day", price: "25,000" },
      { name: "Full Blood Count (FBC)", code: "FBC", turnaround: "Same Day", price: "25,000" },
      { name: "Hemoglobin", code: "HB", turnaround: "Same Day", price: "10,000" },
      { name: "Erythrocyte Sedimentation Rate (ESR)", code: "ESR", turnaround: "Same Day", price: "12,000" },
      { name: "Blood Grouping & Rh Factor", code: "BG-RH", turnaround: "Same Day", price: "15,000" },
      { name: "Peripheral Blood Smear", code: "PBS", turnaround: "Same Day", price: "20,000" },
      { name: "Sickle Cell Screening", code: "SICKLE", turnaround: "Same Day", price: "25,000" },
      { name: "Prothrombin Time (PT)", code: "PT", turnaround: "Same Day", price: "25,000" },
      { name: "INR", code: "INR", turnaround: "Same Day", price: "25,000" },
      { name: "Activated Partial Thromboplastin Time (APTT)", code: "APTT", turnaround: "Same Day", price: "25,000" },
      { name: "Reticulocyte Count", code: "RETIC", turnaround: "Same Day", price: "20,000" },
      { name: "Platelet Count", code: "PLT", turnaround: "Same Day", price: "15,000" },
    ],
    benefits: [
      "Diagnosis of anemia types",
      "Detection of infections",
      "Assessment of clotting disorders",
      "Monitoring blood conditions",
      "Pre-surgical evaluation",
      "Screening for sickle cell disease",
    ],
    preparation: "No special preparation required for most tests. Inform us if you are on blood thinners or have bleeding disorders.",
    image: "/blood-cells-microscope-hematology-medical.jpg",
  },
  {
    id: "microbiology",
    slug: "microbiology",
    icon: Microscope,
    title: "Microbiology",
    fullTitle: "Microbiology Services",
    shortDescription: "Bacterial and fungal infection identification with culture sensitivity testing.",
    description: "Bacterial and fungal infection identification with culture sensitivity testing.",
    detailedDescription: `Microbiology is essential for identifying infectious organisms and determining the most effective treatment. At Star Modern Diagnostic Laboratory, our microbiology department uses advanced culture techniques and automated identification systems to detect bacteria, fungi, and other microorganisms.\n\nOur antimicrobial susceptibility testing helps physicians select the most appropriate antibiotics, combating the growing concern of antibiotic resistance. We maintain strict biosafety protocols and quality standards in all our procedures.`,
    tests: [
      { name: "Urine Culture & Sensitivity", code: "U-CS", turnaround: "2–3 Days", price: "35,000" },
      { name: "Stool Culture & Sensitivity", code: "S-CS", turnaround: "2–3 Days", price: "35,000" },
      { name: "Blood Culture", code: "BC", turnaround: "3–5 Days", price: "50,000" },
      { name: "Wound Swab Culture", code: "WSC", turnaround: "2–3 Days", price: "35,000" },
      { name: "Throat Swab Culture", code: "TSC", turnaround: "2–3 Days", price: "30,000" },
      { name: "Sputum Culture", code: "SPC", turnaround: "2–3 Days", price: "35,000" },
      { name: "Gram Staining", code: "GRAM", turnaround: "Same Day", price: "15,000" },
      { name: "Acid Fast Bacilli Test (AFB)", code: "AFB", turnaround: "Same Day", price: "20,000" },
      { name: "Widal Test", code: "WIDAL", turnaround: "Same Day", price: "20,000" },
      { name: "KOH Preparation", code: "KOH", turnaround: "Same Day", price: "15,000" },
      { name: "Fungal Culture", code: "FC", turnaround: "2–4 Weeks", price: "45,000" },
    ],
    benefits: [
      "Accurate identification of pathogens",
      "Antibiotic sensitivity guidance",
      "Prevention of antibiotic resistance",
      "Targeted treatment approach",
      "Infection monitoring",
      "Hospital infection control support",
    ],
    preparation: "Collect samples before starting antibiotics if possible. Follow specific collection instructions provided by our staff for different sample types.",
    image: "/microbiology-bacteria-culture-petri-dish-laborator.jpg",
  },
  {
    id: "parasitology",
    slug: "parasitology",
    icon: Bug,
    title: "Parasitology",
    fullTitle: "Parasitology Services",
    shortDescription: "Detection of parasitic infections affecting blood, urine, and stool.",
    description: "Detection of parasitic infections affecting blood, urine, and stool.",
    detailedDescription: `Parasitology focuses on the detection and identification of parasites that cause disease in humans. At Star Modern Diagnostic Laboratory, we specialize in diagnosing parasitic infections common in our region, including malaria, intestinal parasites, and other parasitic diseases.\n\nOur experienced microscopists use advanced techniques to detect parasites at various life stages. Early and accurate diagnosis is crucial for effective treatment and preventing complications from parasitic infections.`,
    tests: [
      { name: "Malaria Parasite (Blood Smear)", code: "MP-BS", turnaround: "Same Day", price: "15,000" },
      { name: "Malaria Rapid Diagnostic Test", code: "MP-RDT", turnaround: "Same Day", price: "20,000" },
      { name: "Stool Ova & Parasites", code: "S-OP", turnaround: "Same Day", price: "20,000" },
      { name: "Urine Parasites", code: "U-PAR", turnaround: "Same Day", price: "15,000" },
      { name: "Filariasis Test", code: "FILA", turnaround: "Same Day", price: "25,000" },
      { name: "Giardia Antigen", code: "GIAR", turnaround: "Same Day", price: "30,000" },
      { name: "Cryptosporidium Test", code: "CRYPTO", turnaround: "Same Day", price: "30,000" },
      { name: "Wet Mount Preparation", code: "WMP", turnaround: "Same Day", price: "10,000" },
    ],
    benefits: [
      "Early detection of parasitic infections",
      "Identification of specific parasites",
      "Monitoring of treatment effectiveness",
      "Prevention of complications",
      "Public health surveillance",
      "Support for travel medicine",
    ],
    preparation: "Fresh samples are preferred. Stool samples should be collected in clean containers. For malaria tests, blood is best collected during fever episodes.",
    image: "/parasitology-microscope-blood-smear-malaria.jpg",
  },
  {
    id: "serology-immunology",
    slug: "serology-immunology",
    icon: Shield,
    title: "Serology & Immunology",
    fullTitle: "Serology & Immunology Services",
    shortDescription: "Antibody detection for infections, autoimmune conditions, and immune responses.",
    description: "Antibody detection for infections, autoimmune conditions, and immune responses.",
    detailedDescription: `Serology and immunology involve the study of blood serum and the immune system. At Star Modern Diagnostic Laboratory, we offer a comprehensive range of serological and immunological tests to detect infectious diseases, autoimmune disorders, and assess immune function.\n\nOur tests use advanced techniques including ELISA, immunofluorescence, and rapid immunoassays to detect antibodies and antigens with high sensitivity and specificity. These tests are crucial for diagnosing HIV, hepatitis, and various autoimmune conditions.`,
    tests: [
      { name: "HIV 1 & 2 Antibody Test", code: "HIV", turnaround: "Same Day", price: "25,000" },
      { name: "Hepatitis B Surface Antigen", code: "HBSAG", turnaround: "Same Day", price: "20,000" },
      { name: "Hepatitis C Antibody", code: "HCV", turnaround: "Same Day", price: "25,000" },
      { name: "VDRL (Syphilis)", code: "VDRL", turnaround: "Same Day", price: "15,000" },
      { name: "RPR (Syphilis)", code: "RPR", turnaround: "Same Day", price: "15,000" },
      { name: "Pregnancy Test (Urine)", code: "UPT", turnaround: "Same Day", price: "10,000" },
      { name: "Pregnancy Test (Blood)", code: "BHCG", turnaround: "Same Day", price: "25,000" },
      { name: "C-Reactive Protein (CRP)", code: "CRP", turnaround: "Same Day", price: "20,000" },
      { name: "Rheumatoid Factor (RF)", code: "RF", turnaround: "Same Day", price: "20,000" },
      { name: "ASO Titre", code: "ASO", turnaround: "Same Day", price: "20,000" },
      { name: "ANA (Anti-Nuclear Antibody)", code: "ANA", turnaround: "1–2 Days", price: "45,000" },
      { name: "Dengue NS1 Antigen", code: "DEN-NS1", turnaround: "Same Day", price: "30,000" },
      { name: "Dengue IgM/IgG", code: "DEN-AB", turnaround: "Same Day", price: "35,000" },
    ],
    benefits: [
      "Detection of infectious diseases",
      "Diagnosis of autoimmune conditions",
      "Monitoring immune responses",
      "Screening for chronic infections",
      "Assessment of vaccination status",
      "Support for transplant immunology",
    ],
    preparation: "No special preparation required. Inform us of any recent vaccinations or infections.",
    image: "/serology-immunology-antibody-test-laboratory.jpg",
  },
  {
    id: "hormonal-endocrine",
    slug: "hormonal-endocrine",
    icon: Activity,
    title: "Hormonal & Endocrine",
    fullTitle: "Hormonal & Endocrine Services",
    shortDescription: "Comprehensive hormone level evaluation and endocrine gland function testing.",
    description: "Comprehensive hormone level evaluation and endocrine gland function testing.",
    detailedDescription: `The endocrine system controls many body functions through hormones. At Star Modern Diagnostic Laboratory, we offer comprehensive hormonal and endocrine testing to evaluate thyroid function, reproductive hormones, adrenal function, and other endocrine disorders.\n\nOur hormone tests use advanced immunoassay technology for accurate measurement of hormone levels. These tests are essential for diagnosing conditions like thyroid disorders, diabetes, infertility, and adrenal dysfunction.`,
    tests: [
      { name: "Thyroid Stimulating Hormone (TSH)", code: "TSH", turnaround: "Same Day", price: "25,000" },
      { name: "Free T3", code: "FT3", turnaround: "Same Day", price: "25,000" },
      { name: "Free T4", code: "FT4", turnaround: "Same Day", price: "25,000" },
      { name: "Total T3", code: "TT3", turnaround: "Same Day", price: "20,000" },
      { name: "Total T4", code: "TT4", turnaround: "Same Day", price: "20,000" },
      { name: "Thyroid Panel (TSH, FT3, FT4)", code: "TFT", turnaround: "Same Day", price: "60,000" },
      { name: "Prolactin", code: "PRL", turnaround: "Same Day", price: "30,000" },
      { name: "Testosterone", code: "TEST", turnaround: "Same Day", price: "35,000" },
      { name: "Estrogen (Estradiol)", code: "E2", turnaround: "Same Day", price: "35,000" },
      { name: "Progesterone", code: "PROG", turnaround: "Same Day", price: "35,000" },
      { name: "Luteinizing Hormone (LH)", code: "LH", turnaround: "Same Day", price: "30,000" },
      { name: "Follicle Stimulating Hormone (FSH)", code: "FSH", turnaround: "Same Day", price: "30,000" },
      { name: "Cortisol", code: "CORT", turnaround: "Same Day", price: "35,000" },
      { name: "Insulin", code: "INS", turnaround: "Same Day", price: "40,000" },
      { name: "Vitamin D (25-OH)", code: "VITD", turnaround: "1–2 Days", price: "45,000" },
      { name: "Vitamin B12", code: "B12", turnaround: "1–2 Days", price: "40,000" },
    ],
    benefits: [
      "Diagnosis of thyroid disorders",
      "Evaluation of fertility issues",
      "Assessment of hormonal imbalances",
      "Monitoring hormone therapy",
      "Detection of endocrine tumors",
      "Support for metabolic disorder management",
    ],
    preparation: "Some tests require fasting or specific timing (e.g., morning samples for cortisol). Follow instructions provided by your doctor or our staff.",
    image: "/hormone-endocrine-thyroid-blood-test-laboratory.jpg",
  },
  {
    id: "urinalysis-stool",
    slug: "urinalysis-stool",
    icon: TestTube,
    title: "Urinalysis & Stool",
    fullTitle: "Urinalysis & Stool Analysis Services",
    shortDescription: "Routine urine and stool examinations for infections and metabolic conditions.",
    description: "Routine urine and stool examinations for infections and metabolic conditions.",
    detailedDescription: `Urinalysis and stool analysis are fundamental diagnostic tests that provide valuable information about various body systems. At Star Modern Diagnostic Laboratory, we perform comprehensive urine and stool examinations to detect infections, kidney diseases, digestive disorders, and metabolic conditions.\n\nOur tests include physical examination, chemical analysis, and microscopic examination of samples. These tests are non-invasive yet highly informative, often serving as the first step in diagnosing many conditions.`,
    tests: [
      { name: "Routine Urinalysis", code: "R-UA", turnaround: "Same Day", price: "15,000" },
      { name: "Urine Protein", code: "U-PROT", turnaround: "Same Day", price: "10,000" },
      { name: "Urine Sugar", code: "U-GLU", turnaround: "Same Day", price: "10,000" },
      { name: "Urine Microscopy", code: "U-MICRO", turnaround: "Same Day", price: "15,000" },
      { name: "24-Hour Urine Protein", code: "24H-PROT", turnaround: "Same Day", price: "25,000" },
      { name: "Urine Creatinine", code: "U-CREAT", turnaround: "Same Day", price: "15,000" },
      { name: "Stool Routine Examination", code: "S-RE", turnaround: "Same Day", price: "15,000" },
      { name: "Stool Occult Blood", code: "FOB", turnaround: "Same Day", price: "15,000" },
      { name: "Stool Reducing Substances", code: "S-RS", turnaround: "Same Day", price: "15,000" },
      { name: "Urine Ketones", code: "U-KET", turnaround: "Same Day", price: "10,000" },
      { name: "Urine Bilirubin", code: "U-BILI", turnaround: "Same Day", price: "10,000" },
    ],
    benefits: [
      "Detection of urinary tract infections",
      "Assessment of kidney function",
      "Diagnosis of digestive disorders",
      "Screening for metabolic diseases",
      "Monitoring diabetes management",
      "Non-invasive cancer screening (occult blood)",
    ],
    preparation: "Midstream urine samples are preferred. Fresh stool samples should be delivered within 2 hours of collection. No special diet required unless specified.",
    image: "/urinalysis-urine-test-stool-analysis-laboratory.jpg",
  },
];

export type ServiceData = (typeof servicesData)[number];